export const BANK_SELECT = 'BANK_SELECT';

export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_STATEMENT = 'GET_STATEMENT';
